version: "3.8"
services:
  anythink-backend:
    build: .
    restart: always
    command: sh -c "poetry run alembic upgrade head && poetry run uvicorn --host=0.0.0.0 --port=3000 --reload app.main:app"
    container_name: anythink-backend
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    env_file:
    - .env
    depends_on:
      - "postgres"
  

  # anythink-frontend:
  #   build: ./frontend
  #   container_name: anythink-frontend
  #   command: sh -c "cd frontend && yarn install && yarn start"
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=3001
  #   working_dir: /usr/src
  #   volumes:
  #     - ./:/usr/src/
  #     - /usr/src/frontend/node_modules
  #   ports:
  #     - "3001:3001"

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    logging:
      driver: none
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    env_file:
      - .env
    volumes:
      - ~/posgres/data:/data/db
    ports:
      - '5433:5432'
