version: "3.8"
services:
  anythink-backend-rails:
    build: ./backend
    container_name: anythink-backend-rails
    command: sh -c "cd backend && bundle install && /wait-for-it.sh postgres-rails:5432 -q -t 60 && rm -f /tmp/server.pid && exec rails s -b 0.0.0.0 --pid /tmp/server.pid"

    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - PORT=3000
      - DATABASE_URL=postgres://user:@postgres-rails:5432
    depends_on:
      - "postgres-rails"

  anythink-frontend-react:
    build: ./frontend
    container_name: anythink-frontend-react
    command: sh -c "cd frontend && yarn install && yarn start"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REACT_APP_BACKEND_URL=${CODESPACE_BACKEND_URL:-http://localhost:3000}
      - WDS_SOCKET_PORT=${CODESPACE_WDS_SOCKET_PORT:-3001}
    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
      - /usr/src/frontend/node_modules
    ports:
      - "3001:3001"

  postgres-rails:
    container_name: postgres-rails
    restart: on-failure
    image: postgres
    logging:
      driver: none
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ~/posgres/data:/data/db
    ports:
      - '5433:5432'
