FROM node:16

ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /usr/src/backend/wait-for-it.sh

RUN chmod +x /usr/src/backend/wait-for-it.sh
COPY /backend/node /usr/src/backend
WORKDIR /usr/src/backend
RUN yarn install
