backend:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  image:
    repository: 498915426792.dkr.ecr.us-east-2.amazonaws.com/wilco-backend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

frontend:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  image:
    repository: 498915426792.dkr.ecr.us-east-2.amazonaws.com/wilco-frontend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

mongodb:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  image:
    repository: mongo
    pullPolicy: IfNotPresent
    tag: "latest"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
