apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.database.serviceName }}-0
  name: {{ .Values.database.serviceName }}-0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
