name: Build and deploy to Kubernetes
on:
  push:
    branches:
      - main
      - k8s
jobs:
  check-secret:
    environment: Production
    runs-on: ubuntu-latest
    outputs:
      creds-defined: ${{ steps.creds-defined.outputs.defined }}
    steps:
      - id: creds-defined
        if: "${{ secrets.AWS_ACCESS_KEY_ID != '' && secrets.AWS_SECRET_ACCESS_KEY != '' }}"
        run: echo "::set-output name=defined::true"

  build-backend:
    name: Build backend image
    runs-on: ubuntu-20.04
    needs: [check-secret]
    if: needs.check-secret.outputs.creds-defined == 'true'
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Set branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed  -e 's#/#-#g')"
        id: set_branch

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push backend image to Amazon ECR
        id: build-image-backend
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/wilco-backend:${{ steps.set_branch.outputs.branch }}-${{ github.sha }} \
            -f backend/Dockerfile.aws \
            .
          docker push ${{ steps.login-ecr.outputs.registry }}/wilco-backend:${{ steps.set_branch.outputs.branch }}-${{ github.sha }}

  build-frontend:
    name: Build frontend images
    runs-on: ubuntu-20.04
    needs: [check-secret]
    if: needs.check-secret.outputs.creds-defined == 'true'
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Set branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed  -e 's#/#-#g')"
        id: set_branch

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push frontend image to Amazon ECR
        id: build-image-frontend
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/wilco-frontend:${{ steps.set_branch.outputs.branch }}-${{ github.sha }} \
            -f frontend/Dockerfile.aws \
            .
          docker push ${{ steps.login-ecr.outputs.registry }}/wilco-frontend:${{ steps.set_branch.outputs.branch }}-${{ github.sha }}

  deploy:
    name: Deploy latest tag using helm
    runs-on: ubuntu-20.04
    environment: Production
    needs:
      - build-frontend
      - build-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed  -e 's#/#-#g')"
        id: set_branch

      - name: Create kube config
        run: |
          mkdir -p $HOME/.kube/
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      - name: Install helm
        run: |
          curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
          mv linux-amd64/helm /usr/local/bin/helm
          helm version
      - name: Lint helm charts
        run: helm lint ./charts/app/

      - name: Deploy
        run: |
          helm upgrade --install --timeout 10m app ./charts/app/ \
              --set frontend.image.tag=${{ steps.set_branch.outputs.branch }}-${{ github.sha }} \
              --set backend.image.tag=${{ steps.set_branch.outputs.branch }}-${{ github.sha }}