on: 
  pull_request:
    branches:
      - main

jobs:
  wilco:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Pr checks

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out project
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          working-directory: backend
          bundler-cache: true
          
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Wilco checks
        id: Wilco
        uses: trywilco/actions@main
        with:
          engine: ${{ secrets.WILCO_ENGINE_URL }}
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Check out project
        uses: actions/checkout@v2
      - name: Lint code
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - run: yarn add lint
      - run: yarn lint
