apiVersion: v1
kind: Service
metadata:
  labels:
    app: anythink-frontend-react
  name: anythink-frontend-react
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    app: anythink-frontend-react
