apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: anythink-frontend-react
  name: anythink-frontend-react
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: anythink-frontend-react
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: anythink-frontend-react
    spec:
      containers:
        - args:
            - sh
            - -c
            - cd frontend && yarn install && yarn start
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3001"
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          name: anythink-frontend-react
          ports:
            - containerPort: 3001
              name: http
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      restartPolicy: Always
