apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: anythink-backend-node
  name: anythink-backend-node
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    app: anythink-backend-node
