apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-node
  name: mongodb-node
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb-node
