apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb-node
  name: mongodb-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-node
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb-node
    spec:
      containers:
        - image: mongo
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          name: mongodb-node
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-node-0
      restartPolicy: Always
      volumes:
        - name: mongodb-node-0
          persistentVolumeClaim:
            claimName: mongodb-node-0
