version: "3.9"

services:
  anythink-backend:
    build: ./
    container_name: anythink-backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:3000"
    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
    ports:
      - "3000:3000"
    depends_on:
      - "postgres"

  # anythink-frontend:
  #   build: ./frontend
  #   container_name: anythink-frontend
  #   command: sh -c "cd frontend && yarn install && yarn start"
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=3001
  #   working_dir: /usr/src
  #   volumes:
  #     - ./:/usr/src/
  #     - /usr/src/frontend/node_modules
  #   ports:
  #     - "3001:3001"

  postgres:
     container_name: postgres
     restart: always
     image: postgres
     logging:
       driver: none
     environment:
       POSTGRES_HOST_AUTH_METHOD: trust
       POSTGRES_USER: user
       POSTGRES_PASSWORD: password
       POSTGRES_DB: anythink
     volumes:
       - ~/posgres/data:/data/db
     ports:
       - '5433:5432'
