FROM ruby:2.7.5

RUN apt-get update -qq && apt-get install -y build-essential nodejs

WORKDIR /usr/src
COPY backend ./backend
COPY .wilco ./.wilco

# Pre-install gems
WORKDIR /usr/src/backend
RUN bundle install

