on: 
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Check out project
        uses: actions/checkout@v3
      - name: Lint code
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - run: yarn add lint
      - run: yarn lint
