name: Release
on:
  pull_request:
    types: [closed]
    branches:
      - main
      - 'quest_solution/**'

jobs:
  backup-repo:
    name: Backup repo
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M')"

      - name: Delete previous backup repo
        id: delete_previous_repo
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/{owner}/{repo}
          owner: trywilco
          repo: Anythink-Market-Base-Previous-Version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_WRITE_TOKEN }}

      - name: Create new backup
        id: generate_previous_repo
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{template_owner}/{template_repo}/generate
          template_owner: trywilco
          template_repo: Anythink-Market-Base
          owner: trywilco
          name: Anythink-Market-Base-Previous-Version
          include_all_branches: true
          private: true
          description: Anythink-Market-Base automatic backup, created at ${{ steps.date.outputs.date }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_WRITE_TOKEN }}

  update-quest-solution-branches:
    name: Update quest solution branches
    needs: backup-repo
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .wilco-helpers
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all git history with branches
          token: ${{ secrets.GH_WRITE_TOKEN }}
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Update quest solution branches
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install
      - run: API_SERVER_TOKEN=${{ secrets.API_SERVER_TOKEN }} node scripts/update_child_branches.js --repoPath=. --branch=main --forcePush=true
